### ISSUE TITLE
Move pdf overview into markdown or use the wiki

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-dev-vm#2]
One of the issues I was having when going through this was copy and pasting commands. Does it make more sense to use markdown or some other technology so that I have native text to manipulate?

**Comment by Arithmomaniac** [comment]
This should be closed, as Word files are available:
https://github.com/relativitydev/relativity-dev-vm/tree/master/Documentation/WORD

**Comment by calimetikcura** [comment]
since we have word doc which allows with changes, closing this issue.
