### ISSUE TITLE
missing default-windows-2012r2 image

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-dev-vm#3]
When running the kitchen create command I am seeing the following error:

Failed to complete #create action: [Missing parent_vhd_folder] on default-windows-2012r2

this is blocking me from continuing.

**Comment by calimetikcura** [comment]
you are responsible for creating the image yourself. There are instruction on how to create the image at this link - https://github.com/relativitydev/relativity-dev-vm/blob/master/Documentation/PDF/Relativity%20Dev%20VM%20-%20Create%20Windows%20Base%20Machine%20-%20Documentation.pdf
